export const initialProducts = [
  {
    id: 'prod_1',
    sku: 'EL-001',
    name: 'Wireless Noise-Canceling Earbuds Pro',
    category: 'Electronics',
    costPrice: 850,
    sellingPrice: 1699,
    stock: 24,
    minThreshold: 8,
    unit: 'pcs',
    notes: 'Fast selling, Bluetooth 5.3',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_2',
    sku: 'EL-002',
    name: '65W GaN Fast Charger Multi-Port',
    category: 'Electronics',
    costPrice: 420,
    sellingPrice: 899,
    stock: 15,
    minThreshold: 6,
    unit: 'pcs',
    notes: 'Type-C + USB-A ports',
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_3',
    sku: 'AC-001',
    name: 'Braided Nylon USB-C Cable (2M)',
    category: 'Accessories',
    costPrice: 80,
    sellingPrice: 249,
    stock: 3, // Low stock alert!
    minThreshold: 10,
    unit: 'pcs',
    notes: 'Reinforced connectors',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_4',
    sku: 'EL-003',
    name: '10000mAh Magnetic Power Bank',
    category: 'Electronics',
    costPrice: 750,
    sellingPrice: 1450,
    stock: 0, // Out of stock alert!
    minThreshold: 5,
    unit: 'pcs',
    notes: 'Restock supplier ordered',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_5',
    sku: 'BV-001',
    name: 'Premium Roasted Arabica Coffee (250g)',
    category: 'Beverages',
    costPrice: 180,
    sellingPrice: 380,
    stock: 32,
    minThreshold: 10,
    unit: 'pkts',
    notes: 'Medium dark roast',
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_6',
    sku: 'SN-001',
    name: 'Artisan Salted Caramel Dark Chocolate',
    category: 'Snacks',
    costPrice: 65,
    sellingPrice: 150,
    stock: 45,
    minThreshold: 12,
    unit: 'bars',
    notes: 'Imported cocoa beans',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_7',
    sku: 'AC-002',
    name: 'Matte Glass Screen Protector (iPhone 15/16)',
    category: 'Accessories',
    costPrice: 45,
    sellingPrice: 199,
    stock: 2, // Low stock!
    minThreshold: 15,
    unit: 'pcs',
    notes: 'High profit margin (77%)',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_8',
    sku: 'EL-004',
    name: 'RGB Mechanical Gaming Keyboard',
    category: 'Electronics',
    costPrice: 1400,
    sellingPrice: 2899,
    stock: 8,
    minThreshold: 4,
    unit: 'pcs',
    notes: 'Hot-swappable red switches',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const initialCustomers = [
  {
    id: 'cust_1',
    name: 'Rajesh Sharma',
    phone: '9876543210',
    email: 'rajesh.sharma@example.com',
    address: 'Flat 302, Green Park Apartments',
    totalCredit: 4200,
    totalPaid: 2500,
    currentBalance: 1700,
    lastActivityDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    transactions: [
      {
        id: 'tx_1',
        date: new Date(Date.now() - 15 * 86400000).toISOString(),
        type: 'credit',
        amount: 2500,
        paymentMethod: 'udhaar',
        invoiceNo: 'INV-20250210-4102',
        note: 'Purchased 65W GaN Charger & Earbuds Pro on Udhaar',
      },
      {
        id: 'tx_2',
        date: new Date(Date.now() - 7 * 86400000).toISOString(),
        type: 'payment',
        amount: 1500,
        paymentMethod: 'upi',
        note: 'UPI Payment received via GPay',
      },
      {
        id: 'tx_3',
        date: new Date(Date.now() - 2 * 86400000).toISOString(),
        type: 'credit',
        amount: 1700,
        paymentMethod: 'udhaar',
        invoiceNo: 'INV-20250220-7819',
        note: 'Purchased 2M Braided Cable + Roasted Coffee',
      },
      {
        id: 'tx_4',
        date: new Date(Date.now() - 1 * 86400000).toISOString(),
        type: 'payment',
        amount: 1000,
        paymentMethod: 'cash',
        note: 'Cash payment handed at shop counter',
      }
    ]
  },
  {
    id: 'cust_2',
    name: 'Ananya Verma',
    phone: '9811223344',
    email: 'ananya.v@example.com',
    address: 'Shop 4B, Central Avenue',
    totalCredit: 3200,
    totalPaid: 3200,
    currentBalance: 0, // Fully settled!
    lastActivityDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    transactions: [
      {
        id: 'tx_5',
        date: new Date(Date.now() - 12 * 86400000).toISOString(),
        type: 'credit',
        amount: 3200,
        paymentMethod: 'udhaar',
        invoiceNo: 'INV-20250212-9011',
        note: 'Purchased RGB Mechanical Keyboard on credit',
      },
      {
        id: 'tx_6',
        date: new Date(Date.now() - 5 * 86400000).toISOString(),
        type: 'payment',
        amount: 3200,
        paymentMethod: 'upi',
        note: 'Full settlement via PhonePe',
      }
    ]
  },
  {
    id: 'cust_3',
    name: 'Vikram Mehta',
    phone: '9988776655',
    email: 'vikram.mehta@example.com',
    address: 'B-14, Lake View Residency',
    totalCredit: 2150,
    totalPaid: 500,
    currentBalance: 1650,
    lastActivityDate: new Date(Date.now() - 3 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    transactions: [
      {
        id: 'tx_7',
        date: new Date(Date.now() - 3 * 86400000).toISOString(),
        type: 'credit',
        amount: 2150,
        paymentMethod: 'udhaar',
        invoiceNo: 'INV-20250222-3342',
        note: 'Purchased Wireless Earbuds + Coffee',
      },
      {
        id: 'tx_8',
        date: new Date(Date.now() - 1 * 86400000).toISOString(),
        type: 'payment',
        amount: 500,
        paymentMethod: 'cash',
        note: 'Partial cash payment',
      }
    ]
  }
];

export const initialSales = [
  {
    id: 'sale_1',
    invoiceNo: 'INV-20250227-1011',
    items: [
      {
        productId: 'prod_1',
        sku: 'EL-001',
        name: 'Wireless Noise-Canceling Earbuds Pro',
        quantity: 2,
        costPrice: 850,
        sellingPrice: 1699,
        profit: 1698,
      }
    ],
    totalQuantity: 2,
    totalCost: 1700,
    totalAmount: 3398,
    netProfit: 1698,
    paymentMethod: 'upi',
    paidAmount: 3398,
    pendingAmount: 0,
    customerName: 'Karan Patel',
    customerPhone: '9765432109',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'sale_2',
    invoiceNo: 'INV-20250228-2045',
    items: [
      {
        productId: 'prod_2',
        sku: 'EL-002',
        name: '65W GaN Fast Charger Multi-Port',
        quantity: 1,
        costPrice: 420,
        sellingPrice: 899,
        profit: 479,
      },
      {
        productId: 'prod_3',
        sku: 'AC-001',
        name: 'Braided Nylon USB-C Cable (2M)',
        quantity: 2,
        costPrice: 80,
        sellingPrice: 249,
        profit: 338,
      }
    ],
    totalQuantity: 3,
    totalCost: 580,
    totalAmount: 1397,
    netProfit: 817,
    paymentMethod: 'cash',
    paidAmount: 1397,
    pendingAmount: 0,
    customerName: 'Sneha Rao',
    customerPhone: '9845012345',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'sale_3',
    invoiceNo: 'INV-20250229-3098',
    items: [
      {
        productId: 'prod_8',
        sku: 'EL-004',
        name: 'RGB Mechanical Gaming Keyboard',
        quantity: 1,
        costPrice: 1400,
        sellingPrice: 2899,
        profit: 1499,
      },
      {
        productId: 'prod_6',
        sku: 'SN-001',
        name: 'Artisan Salted Caramel Dark Chocolate',
        quantity: 3,
        costPrice: 65,
        sellingPrice: 150,
        profit: 255,
      }
    ],
    totalQuantity: 4,
    totalCost: 1595,
    totalAmount: 3349,
    netProfit: 1754,
    paymentMethod: 'card',
    paidAmount: 3349,
    pendingAmount: 0,
    customerName: 'Amit Kapoor',
    customerPhone: '9920112233',
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'sale_4',
    invoiceNo: 'INV-20250229-4112',
    items: [
      {
        productId: 'prod_5',
        sku: 'BV-001',
        name: 'Premium Roasted Arabica Coffee (250g)',
        quantity: 2,
        costPrice: 180,
        sellingPrice: 380,
        profit: 400,
      }
    ],
    totalQuantity: 2,
    totalCost: 360,
    totalAmount: 760,
    netProfit: 400,
    paymentMethod: 'upi',
    paidAmount: 760,
    pendingAmount: 0,
    customerName: 'Pooja Nair',
    customerPhone: '9833445566',
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  }
];

export const initialSettings = {
  shopName: 'ProTech & Gourmet Store',
  ownerName: 'Dhyan Shopkeeper',
  currencySymbol: '₹',
  currencyCode: 'INR',
  phone: '+91 98765 43210',
  address: 'Shop 14, Galaxy Commercial Plaza, MG Road',
  lowStockDefaultThreshold: 5,
  upiId: 'protechstore@okhdfcbank',
  gstNumber: '29ABCDE1234F1Z5',
};
